### ISSUE TITLE
+Avogadro's number changed (and AMU with that)

### ISSUE THREAD

**Issue by timbrisc** [ucum-org/ucum#156]
*Issue migrated from trac ticket # 5775*

**component:** unit definitions | **priority:** major

#### 2020-09-16 17:48:55: gschadow@pragmaticdata.com created the issue

___
> Originally from Lynch, Paul (NIH/NLM/LHC) [E] <plynch@mail.nih.gov> for Clem McDonald:
> 
> A needed change to a couple of UCUM constants:
> 
> In 2019 the definition of “mole” was revised (https://en.wikipedia.org/wiki/2019_redefinition_of_the_SI_base_units#Mole) to be exactly 6.02214076×10^23^ (instead of being experimentally determined), but UCUM has an older value of 6.0221367×10^23^. 
> 
> Also, the conversion of an atomic mass unit to g (experimentally determined) needs an update.  Per the 2018 CODATA recommendations (https://physics.nist.gov/cuu/pdf/wallet_2018.pdf) the recommended value is now 1.660 539 066 60(50) × 10^−24^ g.  UCUM has 1.6605402 × 10^-24^.  Note that the “(50)” is the uncertainty on the previous two digits and should not be included in the value.
> 
> The re-definition of a mole as a number affects how conversions between mass and moles are done, because now molecular weight is no longer exactly equal numerically (modulo units) to molar weight, though the difference is very slight (about the 7th significant digit).  However, I don’t think that affects any part of the text in the specification, as far as I can tell.
> 
> So, there is the definition of the two constants to change (“Table 4: SI units”, and “Table 5: Other units…”), and also there are several units in “Table 26: Example Unit Terms by Term” which involve “mol” whose “canonical form value” will need to be revised.
> 
> I don’t know how updates to constants have been handled in the past, but perhaps it is worth considering incrementing the version number of the standard from 2.1 to 2.1.1.

**Comment by timbrisc** [comment]
#### 2020-09-16 17:57:29: gschadow@pragmaticdata.com edited the issue description

**Comment by timbrisc** [comment]
#### 2020-09-16 18:07:33: gschadow@pragmaticdata.com commented


___
> [443] - tentative update of Avogadro's number and definition value of AMU, needs some more checking of text and also needs more commentary to describe the update history and the new official status of the mol."
>

**Comment by timbrisc** [comment]
#### 2021-01-15 03:58:20: simon.cox@csiro.au commented


___
> Table 3. in ​​https://iopscience.iop.org/article/10.1088/1681-7575/aa950a/pdf

**Comment by timbrisc** [comment]
#### 2021-01-15 23:12:30: mitchbre@regenstrief.org changed status from *new* to *assigned*

**Comment by timbrisc** [comment]
#### 2021-01-15 23:12:30: mitchbre@regenstrief.org set owner to *cjmcdonald*

**Comment by timbrisc** [comment]
#### 2021-02-17 17:40:23: mitchbre@regenstrief.org commented


___
> note from Clem:
> we should fix these. Believe it NLM may have changed it in their ucum converter 
>

**Comment by timbrisc** [comment]
#### 2021-02-17 18:53:29: gschadow@pragmaticdata.com commented


___
> This I had already applied in a joint session with the Regenstrief people. [443]

**Comment by timbrisc** [comment]
#### 2021-02-17 19:14:16: simon.cox@csiro.au commented


___
> I didn't see it in the ucum-essence.xml file. 
> But now I understand that 'essence' is not the normative artefact. 
> That was perhaps a misunderstanding on my part. 
> 
> However, I think it also exposes a problem with UCUM - the normative definitions should be available in a machine-processable form, not just a table embedded in an HTML spec. At the least a machine-processable artefact should be automatically synced from the spec.

**Comment by timbrisc** [comment]
#### 2021-03-16 15:45:39: mitchbre@regenstrief.org changed status from *assigned* to *accepted*

**Comment by timbrisc** [comment]
#### 2021-03-16 15:45:39: mitchbre@regenstrief.org changed owner from *cjmcdonald* to *mitchbre*

**Comment by timbrisc** [comment]
#### 2021-03-16 15:45:39: mitchbre@regenstrief.org commented


___
> Decision from 17 February 2021 Board Meeting was to update all constants.

**Comment by timbrisc** [comment]
#### 2021-11-02 19:06:54: mitchbre@regenstrief.org changed title from *Avogadro's number changed (and AMU with that)* to *+Avogadro's number changed (and AMU with that)*

**Comment by dr-shorthair** [comment]
> The Avogadro constant (definition of mole) was already updated to the 2018 value in `ucum-source.xml` and in `ucum.xml`. 
> However, `ucum-essence.xml` and `ucum.html` still have the older value and the latter is what is most visible on the website.

**Comment by timbrisc** [comment]
Need to adjust various mole-based values, e.g. picomole.

**Comment by timbrisc** [comment]
Included in v2.2 release
