### ISSUE TITLE
Add a scope warning into the new-unit template

### ISSUE THREAD

**Issue by dr-shorthair** [ucum-org/ucum#187]
Put a prominent warning about the scope of UCUM in the new-unit request template. 
(To discourage request for non-science units.)

**Comment by timbrisc** [comment]
@dr-shorthair Thank you for this feedback. It is a good suggestion. What do you think of this draft text?

> Note the scope of UCUM is science, healthcare, engineering, and business. Units outside this context are discouraged.

**Comment by dr-shorthair** [comment]
Maybe add the caveat 'but not including currencies' after 'business'. ?

**Comment by timbrisc** [comment]
Thank you, Simon. This scope has been added to the issue template. We are in the process of drafting text for the UCUM site to direct users on making requests.
