### ISSUE TITLE
Relationship to other unit ontologies and standardizations

### ISSUE THREAD

**Issue by cthoyt** [ucum-org/ucum#199]
How does UCUM standard relate to the following resources:

1. https://units-of-measurement.org/
2. Unit Ontology https://obofoundry.org/ontology/uo

To what extent are these redundant?

**Comment by dr-shorthair** [comment]
- https://units-of-measurement.org/ uses UCUM codes as the basis of its own unit URIs - this is acknowledged on the top page. https://units-of-measurement.org/ provides a 'lookup service' for various units representations, using UCUM codes as the common key
- UO was a completely separate initiative under the OBO foundation. It has not had much attention, and the OBO people recognised that there were other systems available that were more comprehensive and better maintained, such as UCUM and QUDT. So they developed https://units-of-measurement.org/ to guide people to the various options and map between them 

So https://units-of-measurement.org/ is definitely not redundant, though UO may be.

**Comment by cthoyt** [comment]
Thanks for the clarification!
