### ISSUE TITLE
formazin turbidity unit

### ISSUE THREAD

**Issue by timbrisc** [ucum-org/ucum#215]
*Issue migrated from trac ticket # 5817*

**component:** organization | **priority:** minor | **keywords:** FTU

#### 2022-06-07 20:19:41: william.hess@fda.hhs.gov created the issue

___
> UCUM Board needs to provide input on this.  Formazin use was first proposed by Kingsbury et al. (1926) for the rapid standardization of turbidity measurements of albumin in urine. The unit is called Formazin Turbidity Unit (FTU). A suspension of 1.25 mg/L hydrazine sulfate and 12.5 mg/L hexamethylenetetramine in water has a turbidity of one FTU.  (https://en.wikipedia.org/wiki/Formazine)
> 
> This new concept is needed to support the U.S. Food and Drug Administration Pharmaceutical Quality Chemistry Manufacturing and Control (PQ/CMC) initiative. Please see https://www.regulations.gov/document/FDA-2022-N-0297-0001, which in part, states:
> 
> "PQ/CMC is a term used to describe manufacturing and testing data of pharmaceutical products. PQ/CMC encompasses topics such as drug stability, quality specification, batch formula, and batch analysis, which are important aspects of drug development. PQ/CMC plays an integral part in the regulatory review process and life cycle management of pharmaceutical products. The development of a structured format for PQ/CMC data will enable consistency in the content and format of PQ/CMC data submitted, thus providing a harmonized language for submission content, allowing reviewers to query the data, and, in general, contributing to a more efficient and effective regulatory decision-making process by creating a standardized data dictionary.
> 
> The impetus for this standardization effort was the provisions from the 2012 Food and Drug Administration Safety and Innovation Act (Pub. L. 112-144), which authorized the Agency to require certain submissions to be submitted in a specified electronic format. PQ/CMC standardization supports FDA's regulatory needs in receiving structured and standardized data in pharmaceutical quality and includes two objectives: (1) To standardize the pharmaceutical quality data that is currently received by FDA in eCTD Module 3 from the sponsoring organizations, and (2) to use these structured elements and develop a FHIR data exchange solution."
>

**Comment by gschadow** [comment]
This should be merged with #220, and #214

Please let us look at related proposals not in isolation. Even the text is re-used between those proposals.

**Comment by timbrisc** [comment]
Included in v2.2 release
