### ISSUE TITLE
Proton mass

### ISSUE THREAD

**Issue by dr-shorthair** [ucum-org/ucum#232]
UCUM spec has proton mass = 1.672 623 1 × 10-24  g
CODATA / NIST has 1.672 621 923 69 x 10-27 kg

https://physics.nist.gov/cgi-bin/cuu/Value?mp

**Comment by gschadow** [comment]
Good luck with your individual pull requests. 

I think all those constants could (should) have been a single update on a single ticket and I think all advisors should be eligible to become committers. 

There were policy documents on the old trac site regarding the stakeholder roles, BTW. 

Clearly we ought to be committers to this git, not doing clones and submit pull requests.

**Comment by dr-shorthair** [comment]
Agreed. I combined them into a single PR already last Wednesday - see https://github.com/ucum-org/ucum/pull/242 
And I closed the individual ones at the same time. 

(Note: it is always possible to close issues and PRs that you opened yourself.)

**Comment by timbrisc** [comment]
Included in v2.2 release
