### ISSUE TITLE
Which is the reference document (file) for UCUM?

### ISSUE THREAD

**Issue by dr-shorthair** [ucum-org/ucum#243]
The Avogadro constant (definition of `mole`) was already updated to the 2018 value in `ucum-source.xml` and in `ucum.xml`. However, `ucum-essence.xml` and `ucum.html` still have the older value and the latter is what is most visible on the website. 

@timbrisc Which is the source-of-truth? What is the process for generating the derived artefacts? 

Related to #242 and #156

**Comment by gschadow** [comment]
Underlying cause of this is #244. We just need to push out a release, that's all.

**Comment by gschadow** [comment]
Where is our ticket adjudication workflow from the old trac site? 

We need to be able to mark this ticket as reject/duplicate or something. We used to have a sophisticated workflow in trac and I was promised that github was better and could do that too. But I don't see any button where I can propose a resolution of this ticket. Unless we have such a thing, we will not be efficient resolving issues as they will just linger on and on.

**Comment by gschadow** [comment]
Finally to your question "which is the reference document" or source of truth? It is ucum-source.xml, nothing else. This ucum-essence.xml is just an automatic extract from the source, and it goes with the releases. If we operate release-free we can also just automatically run the build scripts every time ucum-source.xml is updated.

**Comment by dr-shorthair** [comment]
>  "which is the reference document" or source of truth? It is ucum-source.xml, nothing else

Good. That is where I have been making proposed changes (in my fork, which are then the object of the Pull-requests). 

Regarding your @gschadow questions about GitHub workflow - it can be configured many ways. I was not familiar with the Trac process, which was why I never got far in making proposals. 

In your email you propose all working on a single branch. IMAO that is a bad idea since it does not allow for multiple solutions at different levels of maturity, proposed by different people, to be tested at the same time. Git is rather different to earlier Version Control Systems precisely because it does rely on anyone working on the project keeping their own local 'cache' of the files which is _not_ merged into the main branch until the relevant workflow has been executed. This workflow can be manual, or it can be automated ('continuous integration'), @timbrisc is responsible for getting that up and running. And I think currently he is the only person who can merge changes into the `ucum-org/ucum` repository.

**Comment by dr-shorthair** [comment]
Here's a couple of documents that explain Git Flow and GitHub Flow development strategies: 
https://www.gitkraken.com/learn/git/git-flow
https://docs.github.com/en/get-started/quickstart/github-flow

[This diagram](http://blog.chucklab.com/img/GitFlow.png) captures the Git Flow.

**Comment by gschadow** [comment]
> Regarding your @gschadow questions about GitHub workflow - it can be configured many ways. I was not familiar with the Trac process, which was why I never got far in making proposals.

I don't totally appreciate that. You chose to ignore it just because you demanded to move to git. I agreed to move to git based on the assurance that it could (and would!) do all the things Trac / svn did. So this remains a bug.

I don't think we should go from scratch. The original adjudication workflow that was in place should be implemented here and then we can discuss if anything is wrong with that.

But then that discussion is off topic here, #246 is where that belongs.

This ticket is answered and should be closed.

**Comment by dr-shorthair** [comment]
> You chose to ignore it 

Not exactly. I was unfamiliar with Trac and didn't have time to figure it out. I've no doubt it was a good system. But all version control systems have a learning curve, and I didn't have a project allocation to learn another one for an initiative that was interesting but peripheral to my work at the time. 

> just because you demanded to move to git. 

The UCUM AB was fairly dormant for several years, so when it rebooted with some new membership and leadership, it felt like the right time to at least ask the question about the platform it was hosted on. I _suggested_ Github, because many contemporary open projects, including all the ones I am working on, use Git hosted by GitHub or GitLab. But I wasn't the decision maker here, or even the only one to suggest GitHub.

**Comment by dr-shorthair** [comment]
@gschadow [answered](https://github.com/ucum-org/ucum/issues/243#issuecomment-1272498980)
> "which is the reference document" or source of truth? It is ucum-source.xml, nothing else
