### ISSUE TITLE
New releases of UCUM?

### ISSUE THREAD

**Issue by dr-shorthair** [ucum-org/ucum#244]
Since the UCUM AB is now active, and beginning to approve updates and additions to UCUM, there needs to be a process to update the actual specification document that is visible and available to users and developers. 

Do we envision a continuous release process? Note that this can be automated through GitHub, so that when the source files are updated in the `main` branch, the other files and website gets rebuilt automatically.- right @timbrisc ?

Or will there be an occasional or periodic release, which bundles up all the changes over some period (e.g. 6 months). 

In either case there would need to be a gatekeeper or approval process to merge changes into the `main` branch. It does not have to be heavy ... 

@ehafeza 
@aflackey

**Comment by dr-shorthair** [comment]
For reference: QUDT does a new release approximately monthly.

**Comment by gschadow** [comment]
After #246 and #248 are resolved the question for release is easy. We can move to monthly even, if there are any updates. We can just ratify the change activity on whatever monthly calls. It' a simple routine motion.

Technically the only thing needed is to auto-generate the draft document and other derivatives weekly, daily or on commits. That can be scripted somehow. 

I am sure there is a report of all commits made, we view the diffs. Each commit is associated with a ticket. The ticket is closed when two advisors affirm to close it. (If anyone disagrees later, it can always be opened.) Again, that was all written up in the Lost policy text #247 and was implemented in the Trac workflow #246.

**Comment by dr-shorthair** [comment]
> the question for release is easy. We can move to monthly even, if there are any updates. 

In standard Git Flow a 'release' is often managed by merging the `develop` branch into `main`, and adding a tag.

**Comment by gschadow** [comment]
I sense stagnation. There would be no stagnation if we had a traditional mode with a group of core committers who can operate the levers. I am a bit allergic about being stuck in unworkable workflows when the original workflows from UCUM svn and trac had not been completely ported, and even their documentation memor-holed.

**Comment by timbrisc** [comment]
New release is anticipated in next 30 days.
