### ISSUE TITLE
print symbol for unit gon

### ISSUE THREAD

**Issue by chgessner** [ucum-org/ucum#262]
The print symbol for unit gon should be only the superscript g, i. e. without the leading unicode character #9633 (white square). This is according to https://en.wikipedia.org/wiki/Gradian and applies to ucum-essence and the textual specification.

**Comment by gschadow** [comment]
I am OK with changing that. Does not change the meaning nor anything normative, so this change can simply be applied.

----------------
Vote: approve

**Comment by timbrisc** [comment]
Included in v2.2 release
