### ISSUE TITLE
Image link broken

### ISSUE THREAD

**Issue by plynchnlm** [ucum-org/ucum#287]
On https://ucum.org/ucum, following the BNF in 2.2.10, there is a broken image above the caption, "Figure 1: Pushdown-state automaton describing the syntax."  This seems to be intended to link to the image at https://github.com/ucum-org/ucum/blob/main/assets/images/ucum-state-automaton.gif .

**Comment by timbrisc** [comment]
Thank you for reporting this issue, @plynchnlm . Your timing is impeccable as we are in the process of reorganizing the specification to correct typos/issues, including this. You can expect a resolution to this in February or March. In fact, I plan to contact you directly about some other technical matters regarding UCUM.

I will leave this issue open until it is resolved.

**Comment by timbrisc** [comment]
Included in v2.2 release
